CREATE 
VIEW `vHISTORICA` AS
SELECT 
h.idHISTORIACA,
p.NOMBRE,
h.CODIGO,
h.TRANSACCION,
CONCAT("<img src= '../uploads/'", p.IMG," class='producto-img'>'") AS `FOTO`,
CONCAT(h.FCHTRANSACCION) AS FCHTRANSACCION,
h.TIPOUNIDAD,
h.CANTIDAD,
h.DESCRIPCION,
h.ENTRADAS,
h.SALIDAS,
h.ENTRADAS - h.SALIDAS EXISTENCIA,
p.STOKMINIMO
 FROM historica h, producto p
 where p.idPRODUCTO = h.idPRODUCTO; 